### PR TITLE
Shortening the user agent string

### LINKED ISSUE #66: fetcher errors (TypeError, invalid-json)
After pulling the December changes, I'm seeing the following error multiple times right after MM2 startup:

```
[ERROR] Error initializing fetcher: TypeError: Cannot read property 'getStationName' of undefined
```

When the UI is loaded, the following errors appear:

```
[ERROR] FetchError: invalid json response body at https://bvg-apps-ext.hafas.de/bin/mgate.exe? reason: Unexpected end of JSON input
    at /home/magicmirror/MagicMirror/modules/MMM-PublicTransportBerlin/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async BvgFetcher.getStationName (/home/magicmirror/MagicMirror/modules/MMM-PublicTransportBerlin/BvgFetcher.js:27:19)
    at async Class.createFetcher (/home/magicmirror/MagicMirror/modules/MMM-PublicTransportBerlin/node_helper.js:22:27) {
  type: 'invalid-json'
}
```

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
This should fix #66 by shortening the user agent string.

The other commits are cosmetic changes.

### CODE REVIEW

**Comment by deg0nz** [comment]
Thanks again for this quick fix! I really have no time to fix stuff currently :(

PR Looks good to me. 

Since this is pretty fresh, I just want to ask: Is this ready to merge from your side?

**Comment by KristjanESPERANTO** [comment]
I still get in rare cases an error message `FetchError: invalid json response`. Nevertheless, departures are displayed with this fix.

I would suggest merging the PR because it improves the situation.

File: BvgFetcher.js [hunk 1]
```diff
@@ -4,9 +4,7 @@ const bvgProfile = require("hafas-client/p/bvg");
 const pjson = require("./package.json");
 const bvgClient = createClient(
   bvgProfile,
-  "MagicMirror2 module MMM-PublicTransportBerlin v" +
-    pjson.version +
-    " (https://github.com/deg0nz/MMM-PublicTransportBerlin)"
+  "MMM-PublicTransportBerlin v" + pjson.version
```
Comment (derhuerst) [inline BvgFetcher.js:7]: I suggest to add a installation-specific part to the user agent. This way, admins of the HAFAS API can see that the load they get from Magic Mirrors comes from *mutiple* people/installations, not just one person.

Comment (deg0nz) [reply BvgFetcher.js:7]: Yeah, that's a good idea. But won't we come back to the original problem regarding the long user agent string? 

The MagicMirror creates [`this.identifier` for every module as unique ID](https://docs.magicmirror.builders/development/core-module-file.html#available-module-instance-properties), but as it seems,[ this is only a string containing the index in the module list](https://github.com/MichMich/MagicMirror/blob/26a76f80d63e5c9746b6db712d6901219f8b6b93/js/loader.js#L101).

Comment (derhuerst) [reply BvgFetcher.js:7]: From my experience, a too long user-agent is not a problem, but I haven't specifically looked into it.

Comment (KristjanESPERANTO) [reply BvgFetcher.js:7]: The requests come from different IP addresses. Shouldn't this be obvious enough for the admins that there are different users?

But I am not against adding anything specific to the user agent string :slightly_smiling_face: This could perhaps also be a randomly generated session ID that is created each time the module/mirror is started.

Comment (derhuerst) [reply BvgFetcher.js:7]: > The requests come from different IP addresses. Shouldn't this be obvious enough for the admins that there are different users?

I don't know. But they haven't made the impression of picking effective measures to me. 😄

> But I am not against adding anything specific to the user agent string 🙂 This could perhaps also be a randomly generated session ID that is created each time the module/mirror is started.

Just FYI: [`hafas-client` also randomises the user-agent with every request](https://github.com/public-transport/hafas-client/blob/2ec079adfc8a3d988190491b7e07dc03826b719e/lib/request.js#L88).

Comment (derhuerst) [reply BvgFetcher.js:7]: > > But I am not against adding anything specific to the user agent string 🙂 This could perhaps also be a randomly generated session ID that is created each time the module/mirror is started.
> 
> Just FYI: [`hafas-client` also randomises the user-agent with every request](https://github.com/public-transport/hafas-client/blob/2ec079adfc8a3d988190491b7e07dc03826b719e/lib/request.js#L88).

Ah, maybe a long user-agent *does* make a difference, because a short string will likely be split by `randomizeUserAgent` into 2 reasonably short segments that can't easily be blocked; With increasing length, the likelihood of a long – and therefore unique – segment being among the 2 segments is getting higher.

Comment (KristjanESPERANTO) [reply BvgFetcher.js:7]: > Just FYI: [`hafas-client` also randomises the user-agent with every request](https://github.com/public-transport/hafas-client/blob/2ec079adfc8a3d988190491b7e07dc03826b719e/lib/request.js#L88).

This is interesting :slightly_smiling_face: 

I disabled the randomization process and found the following: As soon as the user agent contains the string `MMM-PublicTransportBerlin`, the query does not work. No matter how long the string is.

So if the hafas-client does not touch this part in its randomization process, the error message appears. This explains why it mostly works with the shorter string (because it is more likely that the string will be changed).

Apparently the queries are not wanted on the endpoint's side. Would it make sense to ask the BVG why they installed the filter? Are there other sources for the data besides the BVG hafas endpoint?

Comment (deg0nz) [reply BvgFetcher.js:7]: Wow, that's definitely a finding.

I could imagine that they have some kind of rating limiter that seems to check for user agents. Fail2ban can be configured that way afaik. 

I could imagine that there are some instances running...

> Are there other sources for the data besides the BVG hafas endpoint?

We could switch back to the VBB-Endpoint, which I wanted to do for some time now. The `hafas-client` with BVG profile was only active because the VBB APIs were very unreliable some years (is it that long ?!) ago.

But I don't know the internals of the hafas APIs, maybe they will block the user agents globally for all profiles.

Comment (derhuerst) [reply BvgFetcher.js:7]: Thanks for investigating this. I'll publish a modified randomisation logic today that doesn't have this problem.

Comment (derhuerst) [reply BvgFetcher.js:7]: > > Are there other sources for the data besides the BVG hafas endpoint?
> 
> We could switch back to the VBB-Endpoint, which I wanted to do for some time now. The `hafas-client` with BVG profile was only active because the VBB APIs were very unreliable some years (is it that long ?!) ago.

The VBB endpoint also has a rate limiting in place. By now, AFAICT, most if not all HAFAS endpoints do.

Comment (derhuerst) [reply BvgFetcher.js:7]: I just published `hafas-client@5.22.2`, which contains a new randomisation logic that inserts a random hex string every 5-10 characters.

Comment (deg0nz) [reply BvgFetcher.js:7]: Noice. Thanks for the quick actions! I will merge this later today with an updated `hafas-client`. Let's hope this works 🤞

Comment (KristjanESPERANTO) [reply BvgFetcher.js:7]: I did the update. Looks good :smiley: 

Thanks @derhuerst :+1: 

But it bothers me that we have to randomize the user-agent at all.

**Comment by deg0nz** [comment]
Thanks again for the support to both of you!
